### ISSUE TITLE
Can''t build

### ISSUE THREAD

**Issue by fdev31** [theICTlab/3DUNDERWORLD-SLS-GPU_CPU#2]
At build time, it fails with:
```
In file included from /tmp/3Dunderworldsls/src/3DUNDERWORLD-SLS-GPU_CPU/src/lib/calibration/Calibrator.cpp:2:0:
/tmp/3Dunderworldsls/src/3DUNDERWORLD-SLS-GPU_CPU/./src/lib/calibration/Calibrator.hpp:41:16: error: 'vector' in namespace 'cv' does not name a template type
     static cv::vector<cv::Point2f> manualMarkCheckBoard(cv::Mat img);
                ^~~~~~
/tmp/3Dunderworldsls/src/3DUNDERWORLD-SLS-GPU_CPU/./src/lib/calibration/Calibrator.hpp:53:41: error: 'cv::vector' has not been declared
                                     cv::vector<cv::Point2f> &camCorners,
                                         ^~~~~~
```

My system is using:

- opencv 3.2
- cuda 8.0
- glm 0.9
- cmake 3.8
- gcc 7.1

**Comment by v3c70r** [comment]
Hi,
I think this is because the OpenCV3 didn't wrap the `std::vector` with `cv::vector` anymore. See this [Stack Overflow post](https://stackoverflow.com/questions/33400823/opencv-3-0-0-cvvector-missing) for details. The quick fix is to use `std::vector` instead of `cv::vector`. The `cv::vector` is only used in calibrator if I remember it correctly.
