### ISSUE TITLE
Question: how might accurate 6DoF external tracking  change capture workflow

### ISSUE THREAD

**Issue by eric-schleicher** [theICTlab/3DUNDERWORLD-SLS-GPU_CPU#4]
If one could use a high speed 6DoF tracking for the camera/projector apparatus how might the capture workflow change?  

would this mean that the user would be able to move freely about the capture object and as long as the apparatus is stable during the projection/capture the pose estimates of the tracking could be used to register the individual scans?

**Comment by v3c70r** [comment]
Hi Eric,

The purpose of this project is to handle one capture. If you can obtain the transformations of captures and map them into captured point clouds, you can easily merge multiple captured point clouds into one point cloud with them.

**Comment by charalambos** [comment]
Dear Eric,

We used to have a high-speed version of this software  [using Phantom Miro 1ex] but we did not pursue its further development because of (a) the 'typically' low resolution of the high-speed cameras [at least the ones we had access to] and (b) the synchronization of camera/projector is non-trivial. 

That said, I agree with Qing's response. You can use the poses between scans to align/merge the reconstructed pointclouds.

Best,

C.

**Comment by eric-schleicher** [comment]
Thank you.  I think it's very promising idea to add automatic registration based on known poses from external tracking.  I will try to achieve this and report back.

**Comment by eric-schleicher** [comment]
![image](https://user-images.githubusercontent.com/8261783/30576323-f4b38022-9cbb-11e7-9f81-1b6ec8318e8e.png)

1920 x 1200 @ 1380fps wasn't high enough resolution?

**Comment by charalambos** [comment]
We had access to Phantom Miro ex1 cameras:
up to 500fps @ 640x480  and the fastest was 1000fps @ 480x360

C.
