### ISSUE TITLE
Clarify: License

### ISSUE THREAD

**Issue by eric-schleicher** [theICTlab/3DUNDERWORLD-SLS-GPU_CPU#5]
This repository is listed as GPLv3, but on the website indicates that: 

![image](https://user-images.githubusercontent.com/8261783/30503957-2bbc528a-9a21-11e7-83f6-ab295811fe36.png)

This is inconsistent with the license terms of the GPLv3  can someone clarify.  As it stands now, commercial use is explicitly allowed in the license.  If none is desired, please provide an update notice for versions moving forward.

**Comment by v3c70r** [comment]
@charalambos is the director of the lab. I think he can answer this question.

**Comment by charalambos** [comment]
Dear Eric,

These are two different versions of the same software: 
- v3.x has now BSD-3 [used to be GPLv3 but changed in order to be included in OpenCV3.x contib]  
- v4 [with GPU support] has GPLv3 license.  

It seems that we forgot to update the website to reflect the changes. Apologies for the mix-up.

Best,

C.

**Comment by eric-schleicher** [comment]
Excellent! 

Thank you for the clarification.  I looks forward to experimenting.
