### ISSUE TITLE
issue building, version of CV

### ISSUE THREAD

**Issue by dimitri80** [theICTlab/3DUNDERWORLD-SLS-GPU_CPU#9]
hello,
I am trying to build this project using VS2017 on a Windows 10 PC.  The build keeps breaking on CV related includes, I am using openCV v4.0, should  i use another version?  Also, I tried to build OpenCV 2.4 but could not configure using cmake, im guessing because of VS2017?  any tips would help.  thanks

**Comment by v3c70r** [comment]
Hi,
Sorry we have only tested it on Ubuntu for now. It should theoretically work on Windows, too. 
You can try to download the OpenCV 2.4 pre-compiled binary from [here](https://opencv.org/releases.html)

**Comment by dimitri80** [comment]
hello,
I have switched over to trying to build this project on Ubuntu 18.04.  I am having issues installing the outdated openCV2.4 instead of openCV3.  As you know there are issues with openCV3, do you recommend a fix for working with openCV3 or maybe downgrading my Ubuntu to 16.4 so I can install openCV2.4.  If you could kindly give the specifications of the OS, openCV built, CUDA version, etc you have successfully built this on, that would help greatly.  thanks

**Comment by v3c70r** [comment]
Hi @dimitri80 ,
I think you can install OpenCV2 from other sources instead of the Ubuntu official one.
For example, you can compile it from the source and direct the cmake search path to your compiled target. ([Here](https://gist.github.com/arthurbeggs/06df46af94af7f261513934e56103b30) is an example to compile it from source, [This command](https://cmake.org/cmake/help/v3.0/variable/CMAKE_PREFIX_PATH.html) can be used to set the library searching path for CMake).
The latest CUDA version should be Ok, but I haven't test it. If my memory is correct, we were using CUDA 7.5 on this project.

**Comment by dimitri80** [comment]
Hi @v3c70r 
Thank you so much for the assistance with this project.  Now that I have an operational setup of 3DUnderworld, I am ready to build out the scanner.  I was wondering if you have any recommendations as to what kind of cameras are best suited for this (full frame? lens type? etc) and what features to look for in a projector as well.  
also, we have a lot of metrology equipment here, and we would like to know if there is a way to incorporate passive reflective targets into the scan data as well, so we can create a coordinate system to place the point cloud into.  has this been done?  
anyways, thank you for the help, look forward to hearing from you.
